language: cpp
sudo: false

linux64_addons:
    addons: &linux64
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - g++-4.8
        - cmake

linux32_addons:
    addons: &linux32
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - g++-4.8
        - cmake
        - g++-4.8-multilib
        - linux-libc-dev:i386
        - libc6-dev-i386

matrix:
  fast_finish: true
  include:
    - name: linux/clang
      os: linux
      compiler: clang
      addons: *linux64
    - name: linux/gcc
      os: linux
      compiler: gcc
      addons: *linux64
    - name: linux/gcc/32-bits
      os: linux
      compiler: gcc
      env: CMAKE_EXTRA="-DHAVE_LIBM=/lib32/libm.so.6 -DCMAKE_CXX_FLAGS=-m32"
      addons: *linux32
    - name: osx/clang
      os: osx
      compiler: clang
    - name: osx/gcc
      os: osx
      compiler: gcc

install:
  # Setting environement
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "${CXX}" == "g++" ]]; then
        export CXX=g++-4.8
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake $CMAKE_ARGS $CMAKE_EXTRA ..
  - make
  - ctest --output-on-failure
